### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by ntwalibas** [LSaldyt/curry#2]
In the abstract of the paper at [Curry: a quantum programming language](https://github.com/LSaldyt/curry/blob/master/paper/paper.pdf), you write: *This project aims to prototype a higher-level, **quantum-hybrid** programming language...* where you might have intended to write *This project aims to prototype a higher-level, **quantum-classical hybrid** programming language...*.

**Comment by LSaldyt** [comment]
Thanks for this! I've fixed the typo. I noticed that you have also been developing a quantum programming language. Feel free to reach out by email if you want to collaborate. My email is my full name, lowercase, with no spaces, at gmail.com

**Comment by LSaldyt** [comment]
I've also created a basic outline of what I'm working on in the Projects tab. Cheers!

**Comment by ntwalibas** [comment]
Thanks for the quick fixes and for reaching out. Will surely email you. Will continue communications from there and the *issues* place for the fine work you are doing here. Cheers!

**Comment by LSaldyt** [comment]
Sounds good! I added some quick documentation today, but ask if you have any questions!
